"""Cells of different sizes on an octree: coupling blocks by the two-scale relation.

A cube of half-width H divides into 8^j cubes of half-width h = H / 2^j.  On a descendant with centre
c_d, the parent's local coordinate is xi_parent = (h / H) xi_child + (c_d - c_parent) / H, and the
polynomials of the parent are polynomials of the same degree in the child's coordinate:

    Q_a(xi_parent) = sum_b C[a, b] Q_b(xi_child)        (``field_reexpansion``),
    m_c(xi_parent) = sum_d D[c, d] m_d(xi_child)        (``source_reexpansion``).

The block between a field cell and a source cell of different sizes is therefore an exact, finite sum of
blocks between EQUAL cells: the larger cell is replaced by its descendants at the smaller cell's size,

    K_ac(large field, small source) = sum over descendants d of  sum_b C_d[a, b] K_bc(d, source),
    K_ac(small field, large source) = sum over descendants d of  sum_e K_ae(field, d) D_d[c, e].

No new integral is needed: every block on the octree comes from the equal-cell blocks of ``blocks``
(closed forms for touching cells, quadrature or the multipole series otherwise).  The cells must be
aligned as octree cells are: sizes in a ratio 2^j, and the larger cell's descendants on the smaller
cell's lattice.

THE SOLVER (``solve_graded_octree``).  The leaves of the tree are cells of mixed sizes.  Each leaf n has
its own half-width h_n, its own projected contrast and its own Gram matrix, and the Galerkin system of
``solver.solve_graded_sphere`` becomes

    M(h_m) psi_m - sum_n K(m, n) E_n psi_n = <Q, psi0>_m,

with K(m, n) from ``octree_block``.  It is assembled densely: the convolution structure that the FFT
solver uses is lost when the cells differ in size.  On a uniform tree it is the uniform solver.
"""

import itertools
import math
from collections.abc import Callable
from dataclasses import dataclass
from functools import cache

import numpy as np
import scipy.linalg
from numpy.polynomial.legendre import leggauss
from numpy.typing import NDArray
from scipy.special import spherical_jn

from ..effective_contrasts import MaterialContrast, ReferenceMedium
from ..sphere_scattering import _plane_wave_strain_voigt
from ..sphere_scattering_fft import _build_grid_index_map
from .basis import (
    CONTRAST_NORMS,
    SOURCE_EXPONENTS_QUARTIC,
    contrast_values,
    gram_test,
    monomials,
    source_expansion,
    source_exponents,
)
from .blocks import coupling_block
from .farfield import radiate
from .fft import _transform, signed_permutations
from .site import cell_contrast_coefficients
from .solver import field_sizes, plane_wave_moments

Triple = tuple[float, float, float]


@cache
def field_reexpansion(n_field: int, scale: float, shift: Triple) -> NDArray:
    """C[a, b] with Q_a(scale * xi + shift) = sum_b C[a, b] Q_b(xi), shape (n_field, n_field).

    By projection onto the orthogonal Q_b with a Gauss rule that is exact for the products.
    """
    x, w = np.polynomial.legendre.leggauss(4)
    xi = np.stack([g.ravel() for g in np.meshgrid(x, x, x, indexing="ij")], axis=1)
    wt = (w[:, None, None] * w[None, :, None] * w[None, None, :]).ravel()
    child = contrast_values(xi)[:n_field]
    parent = contrast_values(scale * xi + np.asarray(shift))[:n_field]
    return (parent * wt) @ child.T / np.array(CONTRAST_NORMS[:n_field])


@cache
def source_reexpansion(n_source: int, scale: float, shift: Triple) -> NDArray:
    """D[c, d] with m_c(scale * xi + shift) = sum_d D[c, d] m_d(xi), shape (n_source, n_source).

    Exactly, by the binomial expansion of (scale * xi_i + shift_i)^e on each axis.
    """
    exps = source_exponents(n_source)
    index = {e: k for k, e in enumerate(exps)}
    out = np.zeros((n_source, n_source))
    for c, e in enumerate(exps):
        axes = [
            [math.comb(e[i], j) * scale**j * shift[i] ** (e[i] - j) for j in range(e[i] + 1)]
            for i in range(3)
        ]
        for j0, j1, j2 in itertools.product(*(range(len(a)) for a in axes)):
            out[c, index[(j0, j1, j2)]] += axes[0][j0] * axes[1][j1] * axes[2][j2]
    return out


class EqualBlocks:
    """Equal-cell blocks K(offset; h) for one frequency and medium, each orbit of the cube group computed
    once (``blocks.coupling_block``) and the rest generated by symmetry (``fft._transform``)."""

    def __init__(self, omega: float, ref: ReferenceMedium, n_source: int = 10, n_test: int = 4) -> None:
        self.omega, self.ref, self.n_source, self.n_test = omega, ref, n_source, n_test
        self._canonical: dict[tuple[float, tuple[int, int, int]], NDArray] = {}
        self._blocks: dict[tuple[float, tuple[int, int, int]], NDArray] = {}

    def __call__(self, offset: tuple[int, int, int], h: float) -> NDArray:
        key = (h, offset)
        if key not in self._blocks:
            a, b, d = sorted((abs(o) for o in offset), reverse=True)
            canon = (a, b, d)
            if (h, canon) not in self._canonical:
                self._canonical[(h, canon)] = coupling_block(
                    canon, h, self.omega, self.ref, self.n_source, self.n_test
                )
            cv, target = np.array(canon, dtype=float), np.array(offset, dtype=float)
            q = next(q for q in signed_permutations() if np.array_equal(q @ cv, target))
            self._blocks[key] = _transform(q, self._canonical[(h, canon)])
        return self._blocks[key]


def _levels_apart(h_large: float, h_small: float) -> int:
    ratio = h_large / h_small
    j = round(math.log2(ratio))
    if j < 0 or abs(2.0**j - ratio) > 1e-9 * ratio:
        raise ValueError(
            f"octree_block: the cell sizes {h_large} and {h_small} are not in a ratio that is a power "
            f"of two "
            f"(ratio {ratio:.6g}). Fix: use cells of an octree, half-widths H / 2^j."
        )
    return j


def _descendants(centre: NDArray, h_large: float, j: int) -> tuple[NDArray, float]:
    """Centres of the 8^j descendants of half-width h_large / 2^j, shape (8^j, 3), and that half-width."""
    m = 2**j
    h = h_large / m
    steps = (2 * np.arange(m) + 1 - m) * h
    grid = np.stack([g.ravel() for g in np.meshgrid(steps, steps, steps, indexing="ij")], axis=1)
    return centre + grid, h


def _offset(c_field: NDArray, c_source: NDArray, h: float) -> tuple[int, int, int]:
    off = (c_field - c_source) / (2.0 * h)
    nearest = np.round(off)
    if np.abs(off - nearest).max() > 1e-9:
        raise ValueError(
            f"octree_block: the cells are not aligned as octree cells: the separation {c_field - c_source} "
            f"is not a whole number of cell widths {2.0 * h}. Fix: place cell centres on the lattice "
            "of the octree."
        )
    return (int(nearest[0]), int(nearest[1]), int(nearest[2]))


def octree_block(
    c_field: Triple,
    h_field: float,
    c_source: Triple,
    h_source: float,
    omega: float,
    ref: ReferenceMedium,
    n_source: int = 10,
    n_test: int = 4,
    equal: EqualBlocks | None = None,
) -> NDArray:
    """K[a, c] between two octree cells of any two sizes, shape (n_test, n_source, 9, 9).

    Args:
        c_field: Centre of the field cell (m).
        h_field: Its half-width (m).
        c_source: Centre of the source cell (m).
        h_source: Its half-width (m).
        omega: Angular frequency (rad/s).
        ref: Background medium.
        n_source: Source monomials (10, 20 or 35).
        n_test: Field functions (4 or 10).
        equal: A cache of equal-cell blocks to draw on (None: each is computed afresh).

    Raises:
        ValueError: when the sizes are not in a ratio 2^j or the cells are not on a common lattice.
    """
    ct, cs = np.asarray(c_field, dtype=float), np.asarray(c_source, dtype=float)

    def eq(offset: tuple[int, int, int], h: float) -> NDArray:
        if equal is not None:
            return equal(offset, h)
        return coupling_block(offset, h, omega, ref, n_source, n_test)

    if h_field >= h_source:
        j = _levels_apart(h_field, h_source)
        if j == 0:
            return eq(_offset(ct, cs, h_source), h_source)
        kids, h = _descendants(ct, h_field, j)
        shifts = (kids - ct) / h_field
        c_mats = np.array([field_reexpansion(n_test, h / h_field, tuple(map(float, s))) for s in shifts])
        blocks = np.array([eq(_offset(kid, cs, h), h) for kid in kids])
        return np.einsum("kab,kbcij->acij", c_mats, blocks)
    j = _levels_apart(h_source, h_field)
    kids, h = _descendants(cs, h_source, j)
    shifts = (kids - cs) / h_source
    d_mats = np.array([source_reexpansion(n_source, h / h_source, tuple(map(float, s))) for s in shifts])
    blocks = np.array([eq(_offset(ct, kid, h), h) for kid in kids])
    return np.einsum("kaeij,kce->acij", blocks, d_mats)


class TreeBlocks:
    """Blocks between octree cells of any two sizes, one computed per orbit of the cube group.

    Two pairs of cells whose relative positions are images of one another under a signed permutation of
    the axes have blocks related by the representations of that permutation (fft._transform), whatever
    the two sizes: the group acts on both cells alike.  Of the pairs of leaves of a tree, almost all are
    such images, so the descent to the smaller size (octree_block) is made once for each orbit.

    Args:
        omega: Angular frequency (rad/s).
        ref: Background medium.
        unit: The length in which relative positions are given (m): the smallest half-width of the tree.
        n_source: Source monomials (10, 20 or 35).
        n_test: Field functions (4 or 10).
        equal: Equal-cell blocks to draw on, for the same frequency, medium and sizes (None: its own).
    """

    def __init__(
        self,
        omega: float,
        ref: ReferenceMedium,
        unit: float,
        n_source: int = 10,
        n_test: int = 4,
        equal: EqualBlocks | None = None,
    ) -> None:
        self.omega, self.ref, self.unit, self.n_source, self.n_test = omega, ref, unit, n_source, n_test
        self.equal = equal if equal is not None else EqualBlocks(omega, ref, n_source, n_test)
        self._canonical: dict[tuple, NDArray] = {}
        self.computed = 0  # canonical blocks between unequal cells computed so far

    def __call__(self, rel: tuple[int, int, int], h_field: float, h_source: float) -> NDArray:
        """K[a, c] for a field cell at rel x unit from the source cell, shape (n_test, n_source, 9, 9)."""
        a, b, d = sorted((abs(o) for o in rel), reverse=True)
        canon = (a, b, d)
        key = (h_field, h_source, canon)
        if key not in self._canonical:
            self._canonical[key] = octree_block(
                (0.0, 0.0, 0.0),
                h_field,
                (-canon[0] * self.unit, -canon[1] * self.unit, -canon[2] * self.unit),
                h_source,
                self.omega,
                self.ref,
                self.n_source,
                self.n_test,
                self.equal,
            )
            self.computed += h_field != h_source
        if tuple(rel) == canon:
            return self._canonical[key]
        cv, target = np.array(canon, dtype=float), np.array(rel, dtype=float)
        q = next(q for q in signed_permutations() if np.array_equal(q @ cv, target))
        return _transform(q, self._canonical[key])


# ---------------------------------------------------------------------------
# Leaves
# ---------------------------------------------------------------------------


def uniform_leaves(radius: float, n_sub: int) -> tuple[NDArray, NDArray]:
    """The uniform grid of ``solver.solve_graded_sphere`` as leaves: (centres (N, 3), half-widths (N,)).

    Every cell of the n_sub^3 grid over [-radius, radius]^3 that overlaps the sphere is kept.
    """
    h_cell = radius / n_sub
    _, centres, h = _build_grid_index_map(
        radius, n_sub, lambda q: bool(np.linalg.norm(q) < radius + np.sqrt(3.0) * h_cell)
    )
    return centres, np.full(len(centres), h)


def refine_leaves(centres: NDArray, half_widths: NDArray, flag: NDArray) -> tuple[NDArray, NDArray]:
    """Replace each flagged leaf by its eight children and keep the others: (centres, half-widths)."""
    signs = np.array(list(itertools.product((-1.0, 1.0), repeat=3)))
    out_c, out_h = [centres[~flag]], [half_widths[~flag]]
    for c, h in zip(centres[flag], half_widths[flag], strict=True):
        out_c.append(c + 0.5 * h * signs)
        out_h.append(np.full(8, 0.5 * h))
    return np.concatenate(out_c), np.concatenate(out_h)


# ---------------------------------------------------------------------------
# The solver
# ---------------------------------------------------------------------------


@dataclass
class OctreeResult:
    """Solution of the Galerkin system on the leaves of an octree, for one plane wave."""

    centres: NDArray  # (N, 3)
    half_widths: NDArray  # (N,)
    omega: float
    ref: ReferenceMedium
    delta: NDArray | list[NDArray]  # per leaf (4 or 10, 9, 9): contrast operator coefficients
    psi: NDArray | list[NDArray]  # per leaf (4 or 10, 9): coefficients of the state
    # arrays when every leaf has the same degrees, lists of per-leaf arrays otherwise
    p: int
    r: int


@dataclass
class _OctreeSystem:
    """The assembled Galerkin system (M - K E) psi = b of a tree, with its per-leaf bookkeeping."""

    a: NDArray  # the dense matrix M - K E
    rhs: NDArray  # the moments b of the incident state
    start: NDArray  # first row of each leaf
    sizes: list  # field_sizes of each leaf
    delta: list  # contrast coefficients of each leaf
    gram: list  # Gram matrix of each leaf's field functions (na x na)
    p_leaf: NDArray
    r_leaf: NDArray


def _assemble_octree(
    omega: float,
    ref: ReferenceMedium,
    contrast: MaterialContrast,
    centres: NDArray,
    half_widths: NDArray,
    profile: Callable[[NDArray], float],
    k_hat: NDArray,
    pol: NDArray,
    wave_type: str,
    p: int | NDArray,
    r: int | NDArray,
    block_cache: dict | None,
) -> _OctreeSystem:
    """Assemble the system of ``solve_graded_octree``; arguments and errors as there."""
    centres = np.asarray(centres, dtype=float)
    half_widths = np.asarray(half_widths, dtype=float)
    n = len(centres)
    p_leaf = np.broadcast_to(np.asarray(p, dtype=int), (n,))
    r_leaf = np.broadcast_to(np.asarray(r, dtype=int), (n,))
    store: dict = block_cache if block_cache is not None else {}
    medium = (float(omega), float(ref.alpha), float(ref.beta), float(ref.rho))
    if store.setdefault("medium", medium) != medium:
        raise ValueError(
            f"solve_graded_octree: block_cache holds blocks for (omega, alpha, beta, rho) = "
            f"{store['medium']}, but this solve has {medium}. Coupling blocks depend on the frequency "
            "and the background. Fix: pass a separate dictionary for each frequency and background, "
            "e.g. block_cache=caches.setdefault(omega, {})."
        )
    sizes = [field_sizes(int(pi), int(ri)) for pi, ri in zip(p_leaf, r_leaf, strict=True)]
    delta = [
        cell_contrast_coefficients(profile, c, float(h), contrast, ref, omega, degree=int(ri))
        for c, h, ri in zip(centres, half_widths, r_leaf, strict=True)
    ]
    rows = np.array([sz[0] * 9 for sz in sizes])
    start = np.concatenate([[0], np.cumsum(rows)])
    a = np.zeros((start[-1], start[-1]), dtype=complex)
    h_min = float(half_widths.min())
    cache_k: dict[tuple, NDArray] = {}
    expansions = [
        source_expansion(d, sz[1])[:, : sz[0]].transpose(0, 2, 1, 3).reshape(sz[3] * 9, sz[0] * 9)
        for d, sz in zip(delta, sizes, strict=True)
    ]
    for col in range(n):
        n_source = sizes[col][3]
        for row in range(n):
            na, n_field = sizes[row][0], sizes[row][1]
            rel = np.round((centres[row] - centres[col]) / h_min).astype(int)
            key = (
                float(half_widths[row]),
                float(half_widths[col]),
                int(rel[0]),
                int(rel[1]),
                int(rel[2]),
                na,
                n_field,
                n_source,
            )
            if key not in cache_k:
                tree_key = ("tree", n_source, n_field, h_min)
                if tree_key not in store:
                    equal = store.setdefault(
                        ("equal", n_source, n_field), EqualBlocks(omega, ref, n_source, n_field)
                    )
                    store[tree_key] = TreeBlocks(omega, ref, h_min, n_source, n_field, equal)
                blk = store[tree_key]((int(rel[0]), int(rel[1]), int(rel[2])), key[0], key[1])
                cache_k[key] = blk[:na].transpose(0, 2, 1, 3).reshape(na * 9, n_source * 9)
            entry = -(cache_k[key] @ expansions[col])
            if row == col:
                entry = entry + np.kron(gram_test(float(half_widths[row]), n_field)[:na, :na], np.eye(9))
            a[start[row] : start[row + 1], start[col] : start[col + 1]] = entry
    k_mag = omega / (ref.alpha if wave_type == "P" else ref.beta)
    k_hat = np.asarray(k_hat, dtype=float) / np.linalg.norm(k_hat)
    amp = np.concatenate([np.asarray(pol, dtype=complex), _plane_wave_strain_voigt(k_hat, pol, k_mag)])
    rhs = np.zeros(start[-1], dtype=complex)
    for i, (c, h, sz) in enumerate(zip(centres, half_widths, sizes, strict=True)):
        mom = plane_wave_moments(c[None, :], float(h), k_mag * k_hat, amp, sz[1])[0, : sz[0]]
        rhs[start[i] : start[i + 1]] = mom.ravel()
    gram = [gram_test(float(h), sz[1])[: sz[0], : sz[0]] for h, sz in zip(half_widths, sizes, strict=True)]
    return _OctreeSystem(a, rhs, start, sizes, delta, gram, p_leaf, r_leaf)


def _octree_result(
    system: _OctreeSystem,
    coeffs: NDArray,
    centres: NDArray,
    half_widths: NDArray,
    omega: float,
    ref: ReferenceMedium,
) -> OctreeResult:
    """Package a vector of leaf coefficients as an OctreeResult."""
    psi = []
    for i, sz in enumerate(system.sizes):
        full = np.zeros((sz[1], 9), dtype=complex)
        full[: sz[0]] = coeffs[system.start[i] : system.start[i + 1]].reshape(sz[0], 9)
        psi.append(full)
    delta = system.delta
    same = len({(f.shape, d.shape) for f, d in zip(psi, delta, strict=True)}) == 1
    return OctreeResult(
        np.asarray(centres, dtype=float),
        np.asarray(half_widths, dtype=float),
        omega,
        ref,
        np.array(delta) if same else delta,
        np.array(psi) if same else psi,
        int(system.p_leaf.max()),
        int(system.r_leaf.max()),
    )


def solve_graded_octree(
    omega: float,
    ref: ReferenceMedium,
    contrast: MaterialContrast,
    centres: NDArray,
    half_widths: NDArray,
    profile: Callable[[NDArray], float],
    k_hat: NDArray,
    pol: NDArray,
    wave_type: str,
    p: int | NDArray = 1,
    r: int | NDArray = 1,
    block_cache: dict | None = None,
) -> OctreeResult:
    """Solve the Galerkin system on leaves of mixed sizes, densely.

    The field degree and the contrast degree may differ from leaf to leaf: a large leaf in a uniform part
    of the medium needs no more than a constant contrast, but it needs a richer basis for the wavefield
    than a small leaf does.

    Args:
        omega: Angular frequency (rad/s).
        ref: Background medium.
        contrast: The contrast that ``profile`` scales.
        centres: Leaf centres, shape (N, 3) (m).
        half_widths: Leaf half-widths, shape (N,) (m), in ratios 2^j.
        profile: Scalar factor of the contrast as a function of position.
        k_hat: Incident direction.
        pol: Incident polarisation.
        wave_type: 'P' or 'S' (the incident speed).
        p: Field degree (0, 1 or 2): one value, or one per leaf.
        r: Contrast degree (0, 1 or 2): one value, or one per leaf.
        block_cache: A dictionary that carries the coupling blocks from one solve to the next (other
            trees, other contrasts, other incident waves).  The blocks depend on the frequency and the
            background only, and the dictionary remembers both.

    Raises:
        ValueError: when block_cache was filled at another frequency or background.
    """
    system = _assemble_octree(
        omega, ref, contrast, centres, half_widths, profile, k_hat, pol, wave_type, p, r, block_cache
    )
    sol = scipy.linalg.solve(system.a, system.rhs, overwrite_a=True, check_finite=False)
    return _octree_result(system, sol, centres, half_widths, omega, ref)


def born_series_octree(
    omega: float,
    ref: ReferenceMedium,
    contrast: MaterialContrast,
    centres: NDArray,
    half_widths: NDArray,
    profile: Callable[[NDArray], float],
    k_hat: NDArray,
    pol: NDArray,
    wave_type: str,
    orders: int,
    p: int | NDArray = 1,
    r: int | NDArray = 1,
    block_cache: dict | None = None,
) -> list[OctreeResult]:
    """The scheme's Born series on a tree, term by term, with no solve.

    The system (M - K E) psi = b gives psi = sum_n psi_n with psi_1 = M^-1 b and
    psi_{n+1} = M^-1 (K E) psi_n, where K E psi = M psi - (M - K E) psi. Term n is the part of the
    scheme's response of order n in the contrast: its far field (``octree_far_field``) is the scheme's
    T_n. Each further term costs one product with the assembled matrix. Arguments as
    ``solve_graded_octree``; ``orders`` is the number of terms returned (psi_1 .. psi_orders).

    Raises:
        ValueError: when orders < 1, or as ``solve_graded_octree``.
    """
    if orders < 1:
        raise ValueError(
            f"born_series_octree: orders = {orders}; at least one term is needed.\n"
            "  Fix: pass orders >= 1 (orders = 2 gives the Born term and the term of second order)."
        )
    system = _assemble_octree(
        omega, ref, contrast, centres, half_widths, profile, k_hat, pol, wave_type, p, r, block_cache
    )

    def m_apply(vec: NDArray, inverse: bool) -> NDArray:
        out = np.empty_like(vec)
        for i, g in enumerate(system.gram):
            blk = vec[system.start[i] : system.start[i + 1]].reshape(g.shape[0], 9)
            out[system.start[i] : system.start[i + 1]] = (
                np.linalg.solve(g, blk) if inverse else g @ blk
            ).ravel()
        return out

    terms = [m_apply(system.rhs, inverse=True)]
    for _ in range(orders - 1):
        prev = terms[-1]
        terms.append(m_apply(m_apply(prev, inverse=False) - system.a @ prev, inverse=True))
    return [_octree_result(system, t, centres, half_widths, omega, ref) for t in terms]


def born_octree(
    omega: float,
    ref: ReferenceMedium,
    contrast: MaterialContrast,
    centres: NDArray,
    half_widths: NDArray,
    profile: Callable[[NDArray], float],
    k_hat: NDArray,
    pol: NDArray,
    wave_type: str,
    p: int | NDArray = 1,
    r: int | NDArray = 1,
) -> OctreeResult:
    """The term of first order in the contrast, with no solve: each leaf holds the projected incident wave.

    The Galerkin system at first order is M psi = <Q, psi0>, so psi is the L2 projection of the incident
    state onto the leaf's field functions.  Its far field (octree_far_field) is the scheme's Born term,
    which costs one pass over the leaves; against the Born term of a finer representation it gives the
    first-order part of the scheme's error before anything is solved.  Arguments as solve_graded_octree.
    """
    centres = np.asarray(centres, dtype=float)
    half_widths = np.asarray(half_widths, dtype=float)
    n = len(centres)
    p_leaf = np.broadcast_to(np.asarray(p, dtype=int), (n,))
    r_leaf = np.broadcast_to(np.asarray(r, dtype=int), (n,))
    k_mag = omega / (ref.alpha if wave_type == "P" else ref.beta)
    k_hat = np.asarray(k_hat, dtype=float) / np.linalg.norm(k_hat)
    amp = np.concatenate([np.asarray(pol, dtype=complex), _plane_wave_strain_voigt(k_hat, pol, k_mag)])
    delta, psi = [], []
    for c, h, pi, ri in zip(centres, half_widths, p_leaf, r_leaf, strict=True):
        na, n_field, _, _ = field_sizes(int(pi), int(ri))
        delta.append(cell_contrast_coefficients(profile, c, float(h), contrast, ref, omega, degree=int(ri)))
        mom = plane_wave_moments(c[None, :], float(h), k_mag * k_hat, amp, n_field)[0, :na]
        full = np.zeros((n_field, 9), dtype=complex)
        full[:na] = np.linalg.solve(gram_test(float(h), n_field)[:na, :na], mom)
        psi.append(full)
    same = len({(f.shape, d.shape) for f, d in zip(psi, delta, strict=True)}) == 1
    return OctreeResult(
        centres,
        half_widths,
        omega,
        ref,
        np.array(delta) if same else delta,
        np.array(psi) if same else psi,
        int(p_leaf.max()),
        int(r_leaf.max()),
    )


def octree_far_field(
    res: OctreeResult, directions: NDArray, r_distance: float, n_gauss: int = 4
) -> tuple[NDArray, NDArray]:
    """Far field (u_P, u_S) of the leaves: each leaf's polynomial source radiated from Gauss nodes."""
    x, w = leggauss(n_gauss)
    xi = np.stack(np.meshgrid(x, x, x, indexing="ij"), -1).reshape(-1, 3)
    ww = np.einsum("i,j,k->ijk", w, w, w).ravel()
    ms = monomials(SOURCE_EXPONENTS_QUARTIC, xi)
    pts, srcs = [], []
    for c, h, d, psi in zip(res.centres, res.half_widths, res.delta, res.psi, strict=True):
        coef = np.einsum("cbij,bj->ci", source_expansion(d, psi.shape[0]), psi)
        srcs.append((ms[: len(coef)].T @ coef) * (ww * h**3)[:, None])
        pts.append(c + h * xi)
    return radiate(np.concatenate(pts), np.concatenate(srcs), res.omega, res.ref, directions, r_distance)


# ---------------------------------------------------------------------------
# Refinement by the detail coefficients of the medium
# ---------------------------------------------------------------------------

N_FUN = {0: 1, 1: 4, 2: 10}


def leaf_energies(
    profile: Callable[[NDArray], NDArray], centres: NDArray, half_widths: NDArray, p: int, levels: int = 3
) -> tuple[NDArray, NDArray, NDArray]:
    """Per leaf: (defect, detail, norm) of a scalar profile against the leaf's polynomials of degree p.

    defect = int (s - P s)^2 over the leaf, P the L2 projection onto the leaf's polynomials, obtained as
    int s^2 - |P s|^2 (orthogonality), with int s^2 from a Gauss rule on the descendants ``levels`` deep;
    detail = |P_children s|^2 - |P s|^2, the energy of the leaf's own detail coefficients, which is what
    one refinement of the leaf recovers; norm = int s^2 (on the fine descendants).

    Args:
        profile: Vectorised: positions (..., 3) to values (...).
        centres: Leaf centres (N, 3).
        half_widths: Leaf half-widths (N,).
        p: Polynomial degree of the cells (0, 1 or 2).
        levels: Depth of the descendants that stand for the exact profile.
    """
    x, w = leggauss(6)
    xi = np.stack([g.ravel() for g in np.meshgrid(x, x, x, indexing="ij")], axis=1)
    wt = (w[:, None, None] * w[None, :, None] * w[None, None, :]).ravel()
    basis = contrast_values(xi)[: N_FUN[p]]
    norms = np.array(CONTRAST_NORMS[: N_FUN[p]])

    def energy(c: NDArray, h: float, depth: int) -> tuple[float, float]:
        kids, hk = _descendants(c, h, depth)
        vals = profile(kids[:, None, :] + hk * xi[None, :, :])
        coef = (vals * wt) @ basis.T / norms
        return float((coef**2 * norms).sum() * hk**3), float(((vals**2) @ wt).sum() * hk**3)

    n = len(centres)
    defect, detail, norm = np.zeros(n), np.zeros(n), np.zeros(n)
    for i, (c, h) in enumerate(zip(centres, half_widths, strict=True)):
        e0, _ = energy(c, float(h), 0)
        e1, _ = energy(c, float(h), 1)
        _, nf = energy(c, float(h), levels)
        defect[i], detail[i], norm[i] = max(nf - e0, 0.0), max(e1 - e0, 0.0), nf
    return defect, detail, norm


def adapt_leaves(
    profile: Callable[[NDArray], NDArray],
    centres: NDArray,
    half_widths: NDArray,
    p: int,
    tol: float,
    h_min: float,
) -> tuple[NDArray, NDArray]:
    """Refine, repeatedly, every leaf whose own detail energy exceeds ``tol`` times the total energy of
    the profile, down to half-width ``h_min``; then drop the leaves on which the profile vanishes.

    The detail energy of a leaf is the part of the projection defect that one refinement of that leaf
    removes, so the rule spends cells where the defect is.
    """
    centres, half_widths = np.asarray(centres, dtype=float), np.asarray(half_widths, dtype=float)
    while True:
        _, detail, norm = leaf_energies(profile, centres, half_widths, p, levels=2)
        flag = (detail > tol * norm.sum()) & (half_widths > h_min * (1.0 + 1e-9))
        if not flag.any():
            keep = norm > 0.0
            return centres[keep], half_widths[keep]
        centres, half_widths = refine_leaves(centres, half_widths, flag)


# ---------------------------------------------------------------------------
# The wave term of a leaf's error
# ---------------------------------------------------------------------------


def born_wave_factor(k_in: NDArray, k_out: NDArray, h: float, p: int) -> float:
    """1 + E_p: a cell's Born far field over its exact one, for a contrast uniform in the cell.

    A cell of half-width h whose field is held to total degree p represents the incident wave
    exp(i k_in.x) by its projection onto the Legendre products of total degree at most p, and radiates
    towards k_out through the projection of exp(-i k_out.x).  With int_{-1}^{1} P_a(xi) exp(i q xi) d xi
    = 2 i^a j_a(q), the ratio of the scheme's first-order far field to the exact one is

        sum_{|a| <= p} prod_i (2 a_i + 1) j_{a_i}(k_in_i h) j_{a_i}(k_out_i h)
        / prod_i j_0((k_in - k_out)_i h),

    which tends to one as p grows (the addition theorem).  For p = 0 the leading departure is
    -(k_in . k_out) (2h)^2 / 12; for degree p it is of order (k h)^(2p + 2).

    Args:
        k_in: Incident wavevector (rad/m), shape (3,).
        k_out: Outgoing wavevector towards the observer, P or S (rad/m), shape (3,).
        h: Half-width of the cell (m).
        p: Field degree of the cell (0, 1 or 2).
    """
    a, b = np.asarray(k_in, dtype=float) * h, np.asarray(k_out, dtype=float) * h
    total = 0.0
    for e in SOURCE_EXPONENTS_QUARTIC[: N_FUN[p]]:
        total += float(
            np.prod([(2 * n + 1) * spherical_jn(n, a[i]) * spherical_jn(n, b[i]) for i, n in enumerate(e)])
        )
    return total / float(np.prod(spherical_jn(0, a - b)))
