#!/usr/bin/env python3
"""Build the Geophysical Journal International version of the paper from the article source.

The article (``../ContinuumLimit.tex``) stays the master; this script regenerates
``ContinuumLimit_GJI.tex`` from it: GJI class and front matter, natbib author-year citations,
the shared BibTeX references (``../references.bib``, style ``gji.bst``), continuous line numbers, and the
data-availability statement GJI requires in place of the article's reproducibility footer.

Run from this directory:  python3 make_gji.py
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = (HERE.parent / "ContinuumLimit.tex").read_text()


def between(text: str, start: str, end: str) -> str:
    a = text.index(start) + len(start)
    return text[a : text.index(end, a)]


abstract = between(SRC, "\\begin{abstract}\n\\noindent\n", "\\end{abstract}").strip()
body = SRC[SRC.index("\\section{Introduction}") : SRC.index("\\vfill\n\\noindent\\rule")].rstrip()
macros = between(SRC, "% --- Macros ---\n", "\\title").strip()

# the article cites through natbib (\citet / \citep) from ../references.bib, so the citations carry over
body = body.replace(
    "\\includegraphics[width=\\linewidth]{convergence.pdf}",
    "\\includegraphics[width=\\linewidth]{../convergence.pdf}",
)
# notebook names: \path breaks at underscores and dots, which GJI's narrower text block needs
body = re.sub(r"\\nb\{([^{}]*)\}", lambda m: r"\path{" + m.group(1).replace(r"\_", "_") + "}", body)
# gji.cls sets its author block with its own tabular preamble, which the array package breaks
RAGGED = r">{\raggedright\arraybackslash}"
ARTICLE_TABLE = "\\begin{center}\n\\begin{tabular}{@{}" + RAGGED + r"p{0.52\linewidth}" + RAGGED
ARTICLE_TABLE += r"p{0.40\linewidth}@{}}"
assert ARTICLE_TABLE in body, "the evidence table's column spec has changed"
GJI_TABLE = (
    "\\begin{center}\\small\\sloppy\n\\begin{tabular}" + r"{@{}p{0.50\linewidth}p{0.48\linewidth}@{}}"
)
body = body.replace(ARTICLE_TABLE, GJI_TABLE)
assert ">{" not in body, "an array-package column spec remains"

PREAMBLE = r"""\documentclass[extra,mreferee]{gji}
% Geophysical Journal International version, generated by make_gji.py from ../ContinuumLimit.tex
\usepackage{amsmath,amssymb,bm}
\usepackage{mathtools}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{placeins}
\usepackage{url}
\usepackage{lineno}
\providecommand{\texorpdfstring}[2]{#1}
\linenumbers
\setcounter{secnumdepth}{3}

"""
FRONT = (
    r"""
\title[Continuum limit of a layer of cubic voxels]{The continuum limit of a space-filling layer of
cubes: a tiling identity, an exact lattice kernel and the closed-form error of the discrete layer}

\author[T. M. Nestor]{T. M. Nestor$^{1}$\\
$^{1}$Independent researcher, Australia}

\date{Received 2026 month day; in original form 2026 month day}
\pagerange{\pageref{firstpage}--\pageref{lastpage}}
\volume{000}
\pubyear{2026}

\begin{document}
\label{firstpage}
\maketitle

\begin{summary}
"""
    + abstract
    + r"""
\end{summary}

\begin{keywords}
Numerical modelling -- Computational seismology -- Wave scattering and diffraction -- Theoretical seismology
\end{keywords}

"""
)
BACK = r"""

\section*{Acknowledgments}
This work began thirty years ago in the author's doctoral research at the Research School of Earth
Sciences of the Australian National University, Canberra \citep{Nestor1996}.

\section*{Data availability}
\sloppy
The Mathematica notebooks that derive and check every result
(\path{Mathematica/ContinuumLimit_*.wl}), the moment integrals of the single site
(\path{Mathematica/CubeMomentCore.wl}, \path{CubeA22Block.wl}, \path{CubeMomentArchiveCheck.wl},
\path{CubeShearSplit.wl}, \path{scripts/gate_cube_shear_split.py} and the test against exact Mie,
\path{scripts/gate_sphere_closure_vs_mie.py} with
\path{Mathematica/SphereClosureDynamic.wl}), the Python reference dumps
and the independent
implementation of the first-moment voxel (\path{scripts/continuum_limit_*.py},
\path{scripts/crosscheck_first_moment_voxel.py}), and the exact normal-incidence kernel
(\path{cubic_scattering/cell_averaged_lattice.py}) are available at \url{https://github.com/tmnestor/MultipleScatteringCalculations}.

\bibliographystyle{gji}
\bibliography{../references}

\label{lastpage}
\end{document}
"""

out = PREAMBLE + macros + "\n" + FRONT + body + BACK
(HERE / "ContinuumLimit_GJI.tex").write_text(out)
print(f"wrote ContinuumLimit_GJI.tex ({len(out.splitlines())} lines)")
