#!/usr/bin/env python3
"""Build the Journal of Computational Physics version of the paper from the article source.

The article (``../ContinuumLimit.tex``) stays the master; this script regenerates ``ContinuumLimit_JCP.tex``
from it: Elsevier's elsarticle class (review mode: double spacing) with line numbers, the front matter in
Elsevier's form (title, author, affiliation, abstract, highlights, keywords), numbered references from the
shared ``../references.bib`` (style ``elsarticle-num-names``), and the closing statements Elsevier asks for.
The abstract is the journal's own: JCP limits it to 250 words and reads a method first.

With ``--submission`` it also assembles ``submission/``: the files to upload to Elsevier's Editorial
Manager, all at ONE folder level (the system rejects LaTeX submissions with subfolders), with the figures
as separate PDF files, and test-compiles them there with pdfLaTeX and BibTeX, as the submission system
does. Only the upload files are kept: the .tex, its .bbl, the .bib, the .bst and the figure PDFs.

Run from this directory:  python3 make_jcp.py [--submission]
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = (HERE.parent / "ContinuumLimit.tex").read_text()


def between(text: str, start: str, end: str) -> str:
    a = text.index(start) + len(start)
    return text[a : text.index(end, a)]


body = SRC[SRC.index("\\section{Introduction}") : SRC.index("\\vfill\n\\noindent\\rule")].rstrip()
macros = between(SRC, "% --- Macros ---\n", "\\title").strip()

FIGURES = [HERE.parent / "convergence.pdf"] + sorted((HERE.parent / "figures").glob("fig_*.pdf"))
# the master's figure paths, relative to its own folder; the local JCP build sits one level down
body = body.replace("{convergence.pdf}", "{../convergence.pdf}").replace(
    "{figures/fig_", "{../figures/fig_"
)
# elsarticle's \paragraph adds its own full stop: drop the source's, or headings end in ".."
body = re.sub(r"\\paragraph\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\.\}", r"\\paragraph{\1}", body)
# notebook names: \path breaks at underscores and dots
body = re.sub(r"\\nb\{([^{}]*)\}", lambda m: r"\path{" + m.group(1).replace(r"\_", "_") + "}", body)

ABSTRACT = r"""
We analyse the convergence of voxel discretisations of the elastic volume integral equation, in
which a medium is divided into cubic cells, each represented by a single-site $T$-matrix and coupled
through the background Green's tensor: the elastic counterpart of the discrete dipole approximation.
Because cubes tile space, a layer of identical voxels is exactly a homogeneous layer, so it isolates
the discretisation error, free of modelling and shape error. We show that (i) the cube's lateral
form factor vanishes on the reciprocal lattice, so the source-cell-averaged coupling equals the
continuum's and the lattice kernel at normal incidence is in closed form; (ii)
the single-site $T$-matrix follows from distributional moments of the Green's tensor and, against
exact scattering by a sphere, is exact statically and departs only by a real, closed-form $(ka)^2$
term; (iii) its self term cancels, so the scheme is a collocation of the continuum equation, of
second order with leading error $+(kd)^2/8$ in reflection and $-(kd)^2/24$ in transmission, which no
scalar correction can remove; (iv) a Galerkin voxel carrying the first moment of its internal field
converges at fourth order, with leading error $-(kd)^4/720$, for incident P, SV and SH waves at
normal and oblique incidence, and its spectral lattice sum needs no Ewald splitting. In a randomly
stratified layer the orders are unchanged, and the fourth-order voxel reaches an accuracy of
$10^{-6}$ with one voxel per model layer. Every result is derived symbolically and verified by an
independent implementation or an exact solution."""
words = len(re.sub(r"\$[^$]*\$", "x", ABSTRACT).split())
assert words <= 250, f"the JCP abstract is {words} words; the limit is 250"

HIGHLIGHTS = [
    "Voxel coupling averaged over the source cell equals the continuum's exactly",
    "The cube's single-site T-matrix follows from distributional moment integrals",
    "The voxel scheme's leading error is known in closed form for every grid",
    "A first-moment voxel converges at fourth order for P, SV and SH waves",
    "In a random stratified layer, one voxel per model layer reaches 1e-6 accuracy",
]
assert all(len(h) <= 85 for h in HIGHLIGHTS), "a highlight exceeds 85 characters"

PREAMBLE = r"""\documentclass[preprint,review,12pt]{elsarticle}
% Journal of Computational Physics version, generated by make_jcp.py from the article ContinuumLimit.tex
\usepackage{amsmath,amssymb,bm}
\usepackage{mathtools}
\usepackage{booktabs}
\usepackage{array}
\usepackage{graphicx}
\usepackage{placeins}
\usepackage{url}
\usepackage{lineno}
\providecommand{\texorpdfstring}[2]{#1}
\setcounter{secnumdepth}{3}
\journal{Journal of Computational Physics}

"""
FRONT = (
    r"""
\begin{document}
\begin{frontmatter}
\title{The continuum limit of a space-filling layer of cubes: a tiling identity, an exact lattice kernel
and the closed-form error of the discrete layer}
\author{T. M. Nestor}
\affiliation{organization={Independent researcher}, country={Australia}}

\begin{abstract}
"""
    + ABSTRACT
    + r"""
\end{abstract}

\begin{highlights}
"""
    + "\n".join(r"\item " + h for h in HIGHLIGHTS)
    + r"""
\end{highlights}

\begin{keyword}
Elastic wave scattering \sep Volume integral equation \sep Foldy--Lax multiple scattering \sep
Discrete dipole approximation \sep Galerkin method \sep Convergence analysis
\end{keyword}
\end{frontmatter}

\linenumbers

"""
)
BACK = r"""

\section*{Acknowledgments}
This work began thirty years ago in the author's doctoral research at the Research School of Earth
Sciences of the Australian National University, Canberra \citep{Nestor1996}.

\section*{Declaration of competing interest}
The author declares no known competing financial interests or personal relationships that could have
appeared to influence the work reported in this paper.

\section*{Data availability}
The Mathematica notebooks and Python scripts that derive and check every result, and the package they
test, are archived at \url{https://doi.org/10.5281/zenodo.23003241} and developed at
\url{https://github.com/tmnestor/MultipleScatteringCalculations}.

\bibliographystyle{elsarticle-num-names}
\bibliography{../references}

\end{document}
"""

out = PREAMBLE + macros + "\n" + FRONT + body + BACK
(HERE / "ContinuumLimit_JCP.tex").write_text(out)
print(f"wrote ContinuumLimit_JCP.tex ({len(out.splitlines())} lines); abstract {words} words")


def assemble_submission() -> None:
    """Write submission/ flat, test-compile it with pdfLaTeX + BibTeX, keep only the upload files."""
    tools = {t: shutil.which(t) for t in ("pdflatex", "bibtex")}
    missing = [t for t, p in tools.items() if p is None]
    if missing:
        raise SystemExit(
            f"cannot test-compile the submission: {', '.join(missing)} not on PATH.\n"
            "Fix: install TeX Live (or TinyTeX) and make sure pdflatex and bibtex are on PATH, then rerun\n"
            "  python3 make_jcp.py --submission"
        )
    sub = HERE / "submission"
    sub.mkdir(exist_ok=True)
    for f in sub.iterdir():
        f.unlink()
    flat = out.replace("{../convergence.pdf}", "{convergence.pdf}").replace("{../figures/fig_", "{fig_")
    flat = flat.replace("\\bibliography{../references}", "\\bibliography{references}")
    assert "../" not in flat, "a relative path to another folder remains in the submission source"
    (sub / "ContinuumLimit_JCP.tex").write_text(flat)
    for src in [HERE.parent / "references.bib", HERE / "elsarticle-num-names.bst", *FIGURES]:
        shutil.copy2(src, sub / src.name)

    def run(*cmd: str) -> None:
        subprocess.run(cmd, cwd=sub, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)

    run(tools["pdflatex"], "-interaction=nonstopmode", "ContinuumLimit_JCP.tex")
    run(tools["bibtex"], "ContinuumLimit_JCP")
    for _ in range(2):
        run(tools["pdflatex"], "-interaction=nonstopmode", "ContinuumLimit_JCP.tex")
    log = (sub / "ContinuumLimit_JCP.log").read_text(errors="replace")
    errors = [ln for ln in log.splitlines() if ln.startswith("! ")]
    undefined = [ln for ln in log.splitlines() if "undefined" in ln]
    if errors or undefined or not (sub / "ContinuumLimit_JCP.pdf").exists():
        raise SystemExit(
            "the submission folder does NOT compile with pdfLaTeX:\n  "
            + "\n  ".join((errors + undefined)[:10])
            + f"\nSee {sub / 'ContinuumLimit_JCP.log'} for the full log."
        )
    keep = {
        "ContinuumLimit_JCP.tex",
        "ContinuumLimit_JCP.bbl",
        "references.bib",
        "elsarticle-num-names.bst",
    }
    keep |= {f.name for f in FIGURES}
    for f in sub.iterdir():
        if f.name not in keep:
            f.unlink()
    print(f"submission/: compiles with pdfLaTeX; upload these {len(keep)} files: {', '.join(sorted(keep))}")


if "--submission" in sys.argv[1:]:
    assemble_submission()
